/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {
    private final static Logger logger = LoggerFactory.getLogger(App.class);

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        logger.info(new App().getGreeting());


    }
}
